name: Install Swift on Linux
description: Installs a Swift toolchain on Linux
author: ser.sofgt GmbH
inputs:
  release-version:
    description: The (released) Swift version (e.g. 5.2.1) to install. If given, `branch-name` and `version-tag` are ignored.
    required: false
  branch-name:
    description: The branch of the Swift version to install (e.g. swift-5.2.1-release). Required if `release-version` is not set!
    required: false
  version-tag:
    description: The version tag of the Swift version to install (e.g. swift-5.2.1-RELEASE). Required if `release-version` is not set!
    required: false
  platform:
    description: The platform for which to install the Swift version (e.g. ubuntu18.04). Note that the github-actions notations with a dash (e.g. ubuntu-20.04) is also valid.
    required: false
  skip-apt:
    description: Whether or not the installation of dependencies (via apt) should be skipped.
    required: false
    default: false
outputs:
  install-path:
    description: The path where Swift was installed.
runs:
  using: node12
  main: dist/index.js
branding:
  color: orange
  icon: cpu
